name: 'Helm3 GitHub Action'
description: 'GitHub Action for running helm'
inputs:
  command:  # id of input
    description: 'Command'
    required: true
  aws_client_id:  # id of input
    description: 'AWS Client ID'
    required: true
  aws_client_secret:  # id of input
    description: 'AWS Client Secret'
    required: true
  cluster_id:  # id of input
    description: 'Cluster ID'
    required: true
  region:  # id of input
    description: 'Cluster region'
    required: true
outputs:
  result: # id of output
    description: 'Result of the output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
